apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erpnext
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.erpnext.com
    chart: erpnext
    targetRevision: "*"
    helm:
      values: |
        mariadb:
          auth:
            rootPassword: root123

        site:
          name: erp.local
          adminPassword: admin123
          installApps:
            - erpnext

        persistence:
          worker:
            storageClass: standard

  destination:
    server: https://kubernetes.default.svc
    namespace: erpnext
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true